name = "Gruvbox"
license = "MIT"
licenselink = "https://github.com/schnerring/hugo-theme-gruvbox/blob/main/LICENSE"
description = "A retro-looking Hugo theme inspired by the gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."
homepage = "https://laaronhooper.github.io/blog/"
demosite = "https://laaronhooper.github.io/blog/"
tags = [
  "blog",
  "dark mode",
  "minimal",
  "personal",
  "responsive"
]
features = ["dark mode"]
min_version = "0.41.0"

[author]
  name = "Luke Hooper"
  homepage = "https://laaronhooper.github.io/blog/"
